export const ROUTING_POLICY = Object.freeze({
  phaseCandidateCount: 9,
  maximumPhaseCandidateCount: 65,
  heuristicSampleCount: 25,
  maxCandidatesPerEdge: 64,
  maximumCandidatesPerEdge: 64,
  maxSearchNodes: 5_000,
  maxMaterializedRouteCandidates: 20_000,
  maxMaterializedSamplePoints: 500_000,
  maxCallMaterializedRouteCandidates: 20_000,
  maxCallMaterializedSamplePoints: 500_000,
  maxBundleValidationChecks: 20_000,
  renderSampleCount: 65,
  maximumRenderSampleCount: 257,
  maximumStandaloneSampleCount: 10_001,
  maximumDistanceOption: 1_000,
  maximumCommonEndpointRadius: 100,
  routeStrokeWidth: 4,
  visualGap: 3.5,
  hardClearance: 7.5,
  preferredClearance: 14,
  commonEndpointRadius: 24,
  verificationTolerance: 0.12,
  verificationClearanceSafetyFactor: 2,
  verificationMaxDepth: 12,
  verificationMaxSegmentsPerRoute: 4096,
});
